#!/bin/bash 

echo
echo "---------------------------------------"
echo "Starting MUD server REPL"
echo "---------------------------------------"
echo 

SERVER_SRC=$(find . -path "*zombunity_server/src")

CLOJURE_JAR=$(find ~/.m2 -name clojure*.jar | sort -r | head -n 1)

REPO_CLASSPATH="$CLOJURE_JAR:$( find ~/.m2 -name *.jar ! -name clojure* | tr -s "\f\n" ":" ):$SERVER_SRC"

# DEBUG
#echo $REPO_CLASSPATH

java -cp $REPO_CLASSPATH clojure.main
