#!/bin/bash 

HSQLDB_PATH=$(find ~/.m2 -name hsqldb*.jar)
SQLTOOL_PATH=$(find ~/.m2 -name sqltool*.jar)

java -cp $SQLTOOL_PATH:$HSQLDB_PATH org.hsqldb.util.DatabaseManagerSwing --rcFile $(find . -name "sqltool.rc") --urlid zombunity 
/*java -cp $SQLTOOL_PATH:$HSQLDB_PATH org.hsqldb.util.DatabaseManagerSwing --help*/

