#!/bin/bash 

custom_echo(){
  echo "=== $1 ===";
}

custom_echo "Starting MUD server REPL"

SERVER_SRC=$(find $(pwd) -path "*zombunity_server/src")

CLOJURE_JAR=$(find ~/.m2 -name clojure-1*.jar | sort -r | head -n 1)

REPO_CLASSPATH="$CLOJURE_JAR:$SERVER_SRC:$( find ~/.m2 -name *.jar ! -name clojure* | tr -s "\f\n" ":" )"
#REPO_CLASSPATH="$CLOJURE_JAR:$SERVER_SRC"

# DEBUG
#echo $REPO_CLASSPATH

java -cp $REPO_CLASSPATH clojure.main -i $SERVER_SRC/zombunity/dispatch.clj -r
