#!/bin/bash 

custom_echo(){
  echo -e "$2=== $1 ===";
}

custom_echo "Running Lein deps"

lein deps

./start_db

./load_data

# will have to do this manually for now
#./start_mud

custom_echo "Compiling ClojureScript to JavaScript"

lein run -m zombunity.build/build

custom_echo "Running Lein deps" "\n"

nohup lein run -m zombunity.http >& ./http.log &

custom_echo "Start MUD server via start_mud_repl"

./start_mud_repl
